In [1]:
import numpy as np

# Pro-indexing

In [3]:
x = np.array([[1, -2, 3, -4],
              [5, 6, 7, -8],
              [9,10,11,12],
              [22,6,4,1],
              [9,7,12,19]])
x.shape

(5, 4)

In [4]:
w = np.array([[0.14,0.42,0.3,0.43],
     [0.23,0.45,0.29,0.7],[0.11,0.945,0.229,0.07]])

In [5]:
r = x.dot(w.T) 
r 

array([[ -1.52 ,  -2.6  ,  -1.373],
       [  1.88 ,   0.28 ,   7.263],
       [ 13.92 ,  18.16 ,  13.799],
       [  7.23 ,   9.62 ,   9.076],
       [ 15.97 ,  22.   ,  11.683]])

In [6]:
y = [0,1,1,2,1]

In [7]:
s = r - r[range(r.shape[0]), y].reshape(-1,1)
s 

array([[  0.   ,  -1.08 ,   0.147],
       [  1.6  ,   0.   ,   6.983],
       [ -4.24 ,   0.   ,  -4.361],
       [ -1.846,   0.544,   0.   ],
       [ -6.03 ,   0.   , -10.317]])

In [8]:
s = np.maximum(s, np.zeros_like(s))
s 

array([[ 0.   ,  0.   ,  0.147],
       [ 1.6  ,  0.   ,  6.983],
       [ 0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.544,  0.   ],
       [ 0.   ,  0.   ,  0.   ]])

In [9]:
s = (s>0) + 0

In [10]:
s

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [11]:
s[range(s.shape[0]), y] = -s.sum(axis=1)

In [12]:
s 

array([[-1,  0,  1],
       [ 1, -2,  1],
       [ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  0,  0]])

In [13]:
x.T.dot(s) 

array([[  4,  12, -16],
       [  8,  -6,  -2],
       [  4, -10,   6],
       [ -4,  17, -13]])

In [14]:
x.T 

array([[ 1,  5,  9, 22,  9],
       [-2,  6, 10,  6,  7],
       [ 3,  7, 11,  4, 12],
       [-4, -8, 12,  1, 19]])

In [16]:
s 

array([[-1,  0,  1],
       [ 1, -2,  1],
       [ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  0,  0]])

In [17]:
r 

array([[ -1.52 ,  -2.6  ,  -1.373],
       [  1.88 ,   0.28 ,   7.263],
       [ 13.92 ,  18.16 ,  13.799],
       [  7.23 ,   9.62 ,   9.076],
       [ 15.97 ,  22.   ,  11.683]])

In [19]:
r.argmax(axis=1) + 1 

array([3, 3, 2, 2, 2])

In [20]:
import itertools

In [21]:
itertools.permutations([1,2],[3,4])

TypeError: Expected int as r

In [22]:
a = np.array([1,2,3])

In [23]:
np.exp(a) 

array([  2.71828183,   7.3890561 ,  20.08553692])

In [47]:
arr = np.ones((7,2))
arr[:, 1] *= 4
arr 

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.]])

In [48]:
m = np.cumsum(np.ones((7,1)))
m 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [49]:
arr = arr * m.reshape(-1, 1) 
arr 

array([[  1.,   4.],
       [  2.,   8.],
       [  3.,  12.],
       [  4.,  16.],
       [  5.,  20.],
       [  6.,  24.],
       [  7.,  28.]])

In [51]:
arr /= np.array(range(1,8)).reshape((-1,1))

In [52]:
arr 

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.]])

-----
# Other

In [2]:
# for auto reloading external modules
%load_ext autoreload
%autoreload 2

In [3]:
# check derivative
from cs231n.classifiers.softmax import softmax_loss_vectorized

In [4]:
q = np.array([0.22, 0.26]).T
x = np.array([0.2, 0.4])

In [5]:
2 * q * x.T 

array([ 0.088,  0.208])

In [11]:
w = np.array([1,2,3,4]).reshape(2,2)
w 

array([[1, 2],
       [3, 4]])

In [12]:
x = np.array((0.5, 3))
x 

array([ 0.5,  3. ])

In [13]:
x.dot(w) 

array([  9.5,  13. ])

In [15]:
y = np.array([0])
y 

array([0])

In [16]:
softmax_loss_vectorized(w, x, y, 0)

AxisError: axis 1 is out of bounds for array of dimension 1