In [2]:
import numpy as np

In [16]:
N = 3
C = 4
H = 2
W = 3
sh = (N, C, H, W)

a = np.random.randint(0, 10, N*C*H*W).reshape(sh) + 1 


# for i in range(a.shape[1]):
#     print(np.pad(a[0, i, ...], pad_width=1, mode='constant')) 

a_padded = np.pad(a,  pad_width=[[0,0], [0,0], [1,1], [1,1]], mode='constant');
a[0,0,0,0] = 0
a 

array([[[[ 0,  2,  8],
         [ 2,  5,  4]],

        [[ 9, 10,  1],
         [ 9,  6,  9]],

        [[ 5,  8,  1],
         [ 3,  3, 10]],

        [[ 3,  3, 10],
         [ 4, 10,  8]]],


       [[[ 6,  1,  3],
         [ 4,  5,  6]],

        [[ 4,  1,  8],
         [ 1,  5,  5]],

        [[ 1,  7,  2],
         [ 1, 10,  4]],

        [[ 2,  4,  1],
         [ 9,  2,  8]]],


       [[[ 4,  8,  4],
         [ 3,  8,  6]],

        [[ 9,  3,  6],
         [ 9,  4,  3]],

        [[10,  3,  6],
         [ 6,  7,  3]],

        [[ 3,  5,  2],
         [10,  3,  3]]]])

In [38]:
a_t = a.transpose((0,2,3,1))
a_t 

array([[[[ 0,  9,  5,  3],
         [ 2, 10,  8,  3],
         [ 8,  1,  1, 10]],

        [[ 2,  9,  3,  4],
         [ 5,  6,  3, 10],
         [ 4,  9, 10,  8]]],


       [[[ 6,  4,  1,  2],
         [ 1,  1,  7,  4],
         [ 3,  8,  2,  1]],

        [[ 4,  1,  1,  9],
         [ 5,  5, 10,  2],
         [ 6,  5,  4,  8]]],


       [[[ 4,  9, 10,  3],
         [ 8,  3,  3,  5],
         [ 4,  6,  6,  2]],

        [[ 3,  9,  6, 10],
         [ 8,  4,  7,  3],
         [ 6,  3,  3,  3]]]])

In [43]:
for_ln = np.split(a_t, C // 2, axis=3)
for_ln[-1].shape

(3, 2, 3, 2)

In [44]:
stacked = np.stack(for_ln)

In [45]:
stacked.shape

(2, 3, 2, 3, 2)

In [46]:
stacked

array([[[[[ 0,  9],
          [ 2, 10],
          [ 8,  1]],

         [[ 2,  9],
          [ 5,  6],
          [ 4,  9]]],


        [[[ 6,  4],
          [ 1,  1],
          [ 3,  8]],

         [[ 4,  1],
          [ 5,  5],
          [ 6,  5]]],


        [[[ 4,  9],
          [ 8,  3],
          [ 4,  6]],

         [[ 3,  9],
          [ 8,  4],
          [ 6,  3]]]],



       [[[[ 5,  3],
          [ 8,  3],
          [ 1, 10]],

         [[ 3,  4],
          [ 3, 10],
          [10,  8]]],


        [[[ 1,  2],
          [ 7,  4],
          [ 2,  1]],

         [[ 1,  9],
          [10,  2],
          [ 4,  8]]],


        [[[10,  3],
          [ 3,  5],
          [ 6,  2]],

         [[ 6, 10],
          [ 7,  3],
          [ 3,  3]]]]])

In [49]:
stacked.mean(axis=-1)

array([[[[ 4.5,  6. ,  4.5],
         [ 5.5,  5.5,  6.5]],

        [[ 5. ,  1. ,  5.5],
         [ 2.5,  5. ,  5.5]],

        [[ 6.5,  5.5,  5. ],
         [ 6. ,  6. ,  4.5]]],


       [[[ 4. ,  5.5,  5.5],
         [ 3.5,  6.5,  9. ]],

        [[ 1.5,  5.5,  1.5],
         [ 5. ,  6. ,  6. ]],

        [[ 6.5,  4. ,  4. ],
         [ 8. ,  5. ,  3. ]]]])

In [50]:
stacked.mean(axis=-1).mean(axis=-1)

array([[[ 5.        ,  5.83333333],
        [ 3.83333333,  4.33333333],
        [ 5.66666667,  5.5       ]],

       [[ 5.        ,  6.33333333],
        [ 2.83333333,  5.66666667],
        [ 4.83333333,  5.33333333]]])

In [63]:
groups_mean = stacked.mean(axis=-1).mean(axis=-1).mean(axis=-1)
groups_mean

array([[ 5.41666667,  4.08333333,  5.58333333],
       [ 5.66666667,  4.25      ,  5.08333333]])

**Проверка:**

In [52]:
stacked.shape

(2, 3, 2, 3, 2)

In [59]:
stacked[0,0,...]

array([[[ 0,  9],
        [ 2, 10],
        [ 8,  1]],

       [[ 2,  9],
        [ 5,  6],
        [ 4,  9]]])

In [58]:
stacked[0,0,...].mean() 

5.416666666666667

In [66]:
stacked[0,1,...]

array([[[6, 4],
        [1, 1],
        [3, 8]],

       [[4, 1],
        [5, 5],
        [6, 5]]])

In [61]:
stacked[0,1,...].mean() 

4.083333333333333

In [62]:
stacked[1,0,...]

array([[[ 5,  3],
        [ 8,  3],
        [ 1, 10]],

       [[ 3,  4],
        [ 3, 10],
        [10,  8]]])

So **stacked** has shape (C//G, N, ..., ..., ...)

Let's try to center data

In [69]:
groups_mean.shape, 'C//G , N'

((2, 3), 'C//G , N')

In [68]:
groups_mean

array([[ 5.41666667,  4.08333333,  5.58333333],
       [ 5.66666667,  4.25      ,  5.08333333]])

In [62]:
stacked[0,0,...]

array([[[ 5,  3],
        [ 8,  3],
        [ 1, 10]],

       [[ 3,  4],
        [ 3, 10],
        [10,  8]]])

In [76]:
stacked[1,0,...] - stacked[1,0,...].mean()

array([[[-0.66666667, -2.66666667],
        [ 2.33333333, -2.66666667],
        [-4.66666667,  4.33333333]],

       [[-2.66666667, -1.66666667],
        [-2.66666667,  4.33333333],
        [ 4.33333333,  2.33333333]]])

In [79]:
centred = stacked - groups_mean[:, :, np.newaxis, np.newaxis, np.newaxis]
centred 

array([[[[[-5.41666667,  3.58333333],
          [-3.41666667,  4.58333333],
          [ 2.58333333, -4.41666667]],

         [[-3.41666667,  3.58333333],
          [-0.41666667,  0.58333333],
          [-1.41666667,  3.58333333]]],


        [[[ 1.91666667, -0.08333333],
          [-3.08333333, -3.08333333],
          [-1.08333333,  3.91666667]],

         [[-0.08333333, -3.08333333],
          [ 0.91666667,  0.91666667],
          [ 1.91666667,  0.91666667]]],


        [[[-1.58333333,  3.41666667],
          [ 2.41666667, -2.58333333],
          [-1.58333333,  0.41666667]],

         [[-2.58333333,  3.41666667],
          [ 2.41666667, -1.58333333],
          [ 0.41666667, -2.58333333]]]],



       [[[[-0.66666667, -2.66666667],
          [ 2.33333333, -2.66666667],
          [-4.66666667,  4.33333333]],

         [[-2.66666667, -1.66666667],
          [-2.66666667,  4.33333333],
          [ 4.33333333,  2.33333333]]],


        [[[-3.25      , -2.25      ],
          [ 2.75      , 

In [86]:
np.concatenate(np.split(centred, 2, axis=0), axis=-1)

array([[[[[-5.41666667,  3.58333333, -0.66666667, -2.66666667],
          [-3.41666667,  4.58333333,  2.33333333, -2.66666667],
          [ 2.58333333, -4.41666667, -4.66666667,  4.33333333]],

         [[-3.41666667,  3.58333333, -2.66666667, -1.66666667],
          [-0.41666667,  0.58333333, -2.66666667,  4.33333333],
          [-1.41666667,  3.58333333,  4.33333333,  2.33333333]]],


        [[[ 1.91666667, -0.08333333, -3.25      , -2.25      ],
          [-3.08333333, -3.08333333,  2.75      , -0.25      ],
          [-1.08333333,  3.91666667, -2.25      , -3.25      ]],

         [[-0.08333333, -3.08333333, -3.25      ,  4.75      ],
          [ 0.91666667,  0.91666667,  5.75      , -2.25      ],
          [ 1.91666667,  0.91666667, -0.25      ,  3.75      ]]],


        [[[-1.58333333,  3.41666667,  4.91666667, -2.08333333],
          [ 2.41666667, -2.58333333, -2.08333333, -0.08333333],
          [-1.58333333,  0.41666667,  0.91666667, -3.08333333]],

         [[-2.58333333,  3

In [ ]:
for_ln = np.split(a_t, C // 2, axis=3)

In [63]:
stride = 1 
ph = 2
pw = 2

h_out = (H - ph) / stride + 1
w_out = (W - pw) / stride + 1

In [64]:
aa = a[0, 0, hi*stride : hi*stride + ph, wi*stride : wi*stride + pw] 
aa 

array([[0, 7],
       [7, 2]])

In [65]:
hi = 0
wi = 0 

ids1 = a[0, 0, hi*stride : hi*stride + ph, wi*stride : wi*stride + pw].argmax(axis=0)
ids2 = a[0, 0, hi*stride : hi*stride + ph, wi*stride : wi*stride + pw].argmax(axis=1)

ids1, ids2 

(array([1, 0]), array([1, 0]))

In [66]:
ids2 

array([1, 0])

In [73]:
idx = a[0, 0, hi*stride : hi*stride + ph, wi*stride : wi*stride + pw].argmax() 
idx 

1

In [76]:
a[0, 0 ,idx // 2, idx % 2] = -1e4
a 

array([[[[     0, -10000,      8,      6],
         [     7,      2,     10,      6],
         [     6,      4,      2,      5]],

        [[     5,      9,      7,      5],
         [     7,      9,      9,      8],
         [     6,      4,     10,      4]],

        [[     9,      1,      2,      7],
         [    10,      9,      5,      6],
         [     7,      6,      5,      1]]],


       [[[     2,      9,      4,      9],
         [     7,      3,      5,      8],
         [     8,      3,      5,      8]],

        [[     7,      2,      4,      2],
         [     9,      1,      4,      6],
         [     9,      6,      6,     10]],

        [[     4,      7,      8,      4],
         [     1,      9,      8,      6],
         [     4,      5,      2,      4]]]])

In [52]:
a[0, [0, 1, 2], [[0], [1]], [[0], [1]]] = -5

In [53]:
a 

array([[[[-5,  4,  2,  7],
         [ 7, -5,  6,  8],
         [ 3,  7,  2,  5]],

        [[-5,  7,  2,  5],
         [ 1, -5, 10,  5],
         [ 9,  2,  3,  7]],

        [[-5,  7,  1,  9],
         [ 9, -5,  1,  3],
         [10, 10,  1,  8]]],


       [[[ 5,  4,  1,  8],
         [ 4,  7,  4,  7],
         [ 4,  8,  5,  3]],

        [[ 2,  6,  5,  9],
         [ 1, 10, 10, 10],
         [ 5,  3,  2,  2]],

        [[ 5,  6,  2,  7],
         [ 2,  7,  3,  4],
         [ 1,  6,  6,  9]]]])

In [159]:
a[:, :, [[0, 1], ]]

array([[[[[99,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25]]],


        [[[31, 32, 33, 34, 35],
          [36, 37, 38, 39, 40]]]],



       [[[[46, 47, 48, 49, 50],
          [51, 52, 53, 54, 55]]],


        [[[61, 62, 63, 64, 65],
          [66, 67, 68, 69, 70]]],


        [[[76, 77, 78, 79, 80],
          [81, 82, 83, 84, 85]]]]])

In [24]:
b = np.random.randn(3,2) * 1000
b 

array([[  433.74004925, -1303.17497002],
       [ -498.76721575,  1736.17106091],
       [ -452.6560357 ,  1922.42350443]])

In [28]:
b 
b[[1, 0]]

array([[ -498.76721575,  1736.17106091],
       [  433.74004925, -1303.17497002]])

In [21]:
ids = [1,2]


b[[1], [0,1]] = np.array([1, 3])
b 

array([[  4.02653552e+02,  -1.10772384e+03],
       [  1.00000000e+00,   3.00000000e+00],
       [  1.31843674e+03,  -7.69876056e+02]])

In [93]:
b.argmax(axis=1)

array([[1, 2],
       [2, 1]])

In [50]:
np.argmax(a, axis=0)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [38]:
a[-1, :, 1:-1, 1:-1]

array([[[46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]],

       [[61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75]],

       [[76, 77, 78, 79, 80],
        [81, 82, 83, 84, 85],
        [86, 87, 88, 89, 90]]])

In [12]:
a_pad = np.pad(a, 1, 'constant', constant_values=())
a_pad 

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [11]:
a_pad[1:3, 1:3]

array([[0, 1],
       [4, 5]])

In [7]:
a.repeat(3, axis=0).reshape(3, -1).T 

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [11]:
np.tile(-a, 3).reshape(3, -1)


array([[ 0, -1, -2],
       [ 0, -1, -2],
       [ 0, -1, -2]])

In [13]:
a = (1,2)
a + (3,)

(1, 2, 3)

In [12]:
np.std(np.random.randn(10000) * 8)

8.0855850110791145

In [29]:
d = {'a' : 1, 'b' : 2, 'd' : 9}

c = d.pop('c', 5)
a = d.pop('a', 3)

c, a, d

(5, 1, {'b': 2, 'd': 9})

In [20]:
a = np.arange(10) * 11 
a 

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [25]:
np.random.choice(10, 11, True)

array([8, 8, 9, 2, 3, 6, 5, 1, 2, 4, 4])

In [26]:
a[8:30]

array([88, 99])

In [28]:
np.vstack(a)

array([[ 0],
       [11],
       [22],
       [33],
       [44],
       [55],
       [66],
       [77],
       [88],
       [99]])

In [31]:
for i in d:
    print(i) 

b
d


In [32]:
for i in range(9, 0, -1):
    print(i) 

9
8
7
6
5
4
3
2
1


In [42]:
arr = np.arange(9)
d['hello'] = arr.copy() 
d 

{'b': 2, 'd': 9, 'hello': array([0, 1, 2, 3, 4, 5, 6, 7, 8])}

In [43]:
arr *= 10

In [47]:
d 

{'b': 2, 'd': 9, 'hello': array([0, 1, 2, 3, 4, 5, 6, 7, 8])}

In [49]:
d.get('h', 19)

19

In [52]:
d.setdefault('b', 90)
d.setdefault('hue', 88)
d 

{'b': 2, 'd': 9, 'hello': array([0, 1, 2, 3, 4, 5, 6, 7, 8]), 'hue': 88}

In [53]:
np.random.

7